name: React-Project-CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code #gets pre build actions 
      uses: actions/checkout@v2
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t mero/react-project:latest .
    - run: docker run -e CI=true mero/react-project:latest npm test

    